/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.players.view;


import com.model.bean.Personal;
import com.model.dao.PersonalDAO;
import java.util.function.Consumer;
import javax.swing.table.DefaultTableModel;

    
/**
 *
 * @author Gabriel
 */
public class telapersonal extends javax.swing.JFrame {

    /**
     * Creates new form telapersonal
     */
    public telapersonal() {
        initComponents();
        readJTable();
    }
    
    public void readJTable() {

        DefaultTableModel modelo = (DefaultTableModel) jTablePersonal.getModel();
        modelo.setNumRows(0);
        PersonalDAO vdao = new PersonalDAO();
        for (Personal p : vdao.FindAll()) {
            modelo.addRow(new Object[]{
                p.getIdPersonal(),
                p.getNome(),
                p.getAtividades(),
                p.getPeriodo(),
                p.getCref()
                
            });

        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtIdade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        txtCep = new javax.swing.JTextField();
        txtSexo = new javax.swing.JTextField();
        cmbAtividades = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cmbPeriodo = new javax.swing.JComboBox<>();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jLabel12 = new javax.swing.JLabel();
        txtCref = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePersonal = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("CADASTRO PERSONAL ACADEMIA ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));
        jLabel2.getAccessibleContext().setAccessibleName("txtNome");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 315, -1));
        txtNome.getAccessibleContext().setAccessibleName("txtNome");

        jLabel3.setText("Idade:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));
        jLabel3.getAccessibleContext().setAccessibleName("");

        getContentPane().add(txtIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 315, -1));
        txtIdade.getAccessibleContext().setAccessibleName("txtIdade");

        jLabel4.setText("Endereço:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        jLabel5.setText("Bairro:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 34, -1));

        jLabel6.setText("Cidade:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        jLabel7.setText("Telefone:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        jLabel8.setText("Cep:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        jLabel9.setText("Sexo:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, -1));

        jLabel10.setText("Quais atividades deseja dar aula?");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, -1, -1));
        getContentPane().add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 298, -1));
        txtEndereco.getAccessibleContext().setAccessibleName("txtEndereco");

        getContentPane().add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 298, -1));
        txtBairro.getAccessibleContext().setAccessibleName("txtBairro");

        getContentPane().add(txtCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 298, -1));
        txtCidade.getAccessibleContext().setAccessibleName("txtCidade");

        getContentPane().add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 298, -1));
        txtTelefone.getAccessibleContext().setAccessibleName("txtTelefone");

        getContentPane().add(txtCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 298, -1));
        txtCep.getAccessibleContext().setAccessibleName("txtCep");

        getContentPane().add(txtSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, 103, -1));
        txtSexo.getAccessibleContext().setAccessibleName("txtSexo");

        cmbAtividades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Musculação", "Pilates", "Crossfit", "Luta" }));
        getContentPane().add(cmbAtividades, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, -1, -1));

        jLabel11.setText("Qual horario deseja dar aula?");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, -1, -1));

        cmbPeriodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manha ", "Tarde", "Noite" }));
        cmbPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPeriodoActionPerformed(evt);
            }
        });
        getContentPane().add(cmbPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, -1, -1));

        jToggleButton1.setText("SALVAR");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));

        jToggleButton2.setText("EXCLUIR");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, -1, -1));

        jToggleButton3.setText("CANCELAR");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, -1, -1));

        jLabel12.setText("N° CREF:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, -1, -1));

        txtCref.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCrefActionPerformed(evt);
            }
        });
        getContentPane().add(txtCref, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 103, -1));

        jTablePersonal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Atividades", "Periodo"
            }
        ));
        jTablePersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePersonalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePersonal);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 660, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
 
    
    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
cadastrapersonal();         // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
excluipersonal();        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
System.exit(0);         // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void txtCrefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCrefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCrefActionPerformed

    private void jTablePersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePersonalMouseClicked
       if (jTablePersonal.getSelectedRow() != -1){
           txtNome.setText(jTablePersonal.getValueAt(jTablePersonal.getSelectedRow(), 1).toString());
           txtCref.setText(jTablePersonal.getValueAt(jTablePersonal.getSelectedRow(), 2).toString());
           txtIdade.setText(jTablePersonal.getValueAt(jTablePersonal.getSelectedRow(), 3).toString());
           txtSexo.setText(jTablePersonal.getValueAt(jTablePersonal.getSelectedRow(), 4).toString());
           txtEndereco.setText(jTablePersonal.getValueAt(jTablePersonal.getSelectedRow(), 5).toString());
           txtBairro.setText(jTablePersonal.getValueAt(jTablePersonal.getSelectedRow(), 6).toString());
           txtCidade.setText(jTablePersonal.getValueAt(jTablePersonal.getSelectedRow(), 7).toString());
           txtTelefone.setText(jTablePersonal.getValueAt(jTablePersonal.getSelectedRow(), 8).toString());
           txtCep.setText(jTablePersonal.getValueAt(jTablePersonal.getSelectedRow(), 9).toString());
           cmbPeriodo.setSelectedItem(jTablePersonal.getValueAt(jTablePersonal.getSelectedRow(), 10).toString());
           cmbAtividades.setSelectedItem(jTablePersonal.getValueAt(jTablePersonal.getSelectedRow(), 11).toString());
           
           
           
       }
   
    }//GEN-LAST:event_jTablePersonalMouseClicked

    private void cmbPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPeriodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPeriodoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telapersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telapersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telapersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telapersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telapersonal().setVisible(true);
            }
        });
    }
    
      private void cadastrapersonal() {
        Personal p = new Personal();
        PersonalDAO vdao = new PersonalDAO();
        p.setNome(txtNome.getText());
        p.setSexo(txtSexo.getText());
        p.setIdade(txtIdade.getText());
        p.setEndereco(txtEndereco.getText());
        p.setBairro(txtBairro.getText());
        p.setCidade(txtCidade.getText());
        p.setTelefone(txtTelefone.getText());
        p.setCep(txtCep.getText());
        p.setPeriodo(cmbPeriodo.getSelectedItem().toString());
        p.setAtividades(cmbAtividades.getSelectedItem().toString());
        p.setCref(txtCref.getText());
        
        vdao.save(p);
        limpa();
        readJTable();
    }
      
       private void excluipersonal(){
        PersonalDAO pdao = new PersonalDAO();
        pdao.remove((int) jTablePersonal.getValueAt(jTablePersonal.getSelectedRow(), 0));
        limpa();
        readJTable();
    }
       
       private void atualizapersonal() {
        Personal p = new Personal();
        PersonalDAO pdao = new PersonalDAO();
        p.setIdPersonal((int) jTablePersonal.getValueAt(jTablePersonal.getSelectedRow(), 0));
        p.setNome(txtNome.getText());
        p.setSexo(txtSexo.getText());
        p.setIdade(txtIdade.getText());
        p.setEndereco(txtEndereco.getText());
        p.setBairro(txtBairro.getText());
        p.setCidade(txtCidade.getText());
        p.setTelefone(txtTelefone.getText());
        p.setCep(txtCep.getText());
        p.setPeriodo(cmbPeriodo.getSelectedItem().toString());
        p.setAtividades(cmbAtividades.getSelectedItem().toString());
        p.setCref(txtCref.getText());
        
        pdao.update(p);
        limpa();
        readJTable();
    }
       
        private void limpa() {
        txtNome.setText(null);
        txtSexo.setText(null);
        txtIdade.setText(null);
        txtEndereco.setText(null);
        txtBairro.setText(null);
        txtCidade.setText(null);
        txtTelefone.setText(null);
        txtCep.setText(null);
        cmbPeriodo.setSelectedItem(null);
        cmbAtividades.setSelectedItem(null);
        txtCref.setText(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbAtividades;
    private javax.swing.JComboBox<String> cmbPeriodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePersonal;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCref;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSexo;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
